version: '3'

services:
  python-service:
    image: python:3.9
    volumes:
      - ./app:/app
    working_dir: /app
    # command: python script.py
    tty: true

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8097:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
    volumes:
      - ./weaviate-data:/var/lib/weaviate

  weaviate-console:
    image: semitechnologies/weaviate-console:latest
    ports:
      - "8081:80"
    environment:
      - WEAVIATE_URI=http://weaviate:8080