version: '3'

services:
  python-service:
    image: python:3.9
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true

  weaviate:
    image: semitechnologies/weaviate:1.23.9
    ports:
     - 8097:8080
     - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      ENABLE_MODULES: text2vec-transformers
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable

  weaviate-console:
    image: semitechnologies/weaviate-console:latest
    ports:
      - "8081:80"
    environment:
      - WEAVIATE_URI=http://weaviate:8080